config/routes.rb
Rails.application.routes.draw do
  resources :envios
  resources :categoria
  resources :detalles_venta
  resources :venta
  resources :productos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/venta.rb
class Venta < ApplicationRecord
  belongs_to :cliente
  has_many :detalles_ventas
  has_one :envio
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_ventum, only: %i[ show edit update destroy ]

  # GET /venta or /venta.json
  def index
    @venta = Venta.all
  end

  # GET /venta/1 or /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @ventum = Venta.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta or /venta.json
  def create
    @ventum = Venta.new(ventum_params)

    respond_to do |format|
      if @ventum.save
        format.html { redirect_to @ventum, notice: "Ventum was successfully created." }
        format.json { render :show, status: :created, location: @ventum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1 or /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: "Ventum was successfully updated." }
        format.json { render :show, status: :ok, location: @ventum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1 or /venta/1.json
  def destroy
    @ventum.destroy!

    respond_to do |format|
      format.html { redirect_to venta_path, status: :see_other, notice: "Ventum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Venta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ventum_params
      params.require(:ventum).permit(:cliente_id, :fecha, :total, :metodo_pago, :estado)
    end
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/venta/_form.html.erb
<%= form_with(model: @venta) do |form| %>
  <% if @venta.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@venta.errors.count, "error") %> prohibited this venta from being saved:</h2>

      <ul>
        <% @venta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.number_field :cliente_id %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.label :metodo_pago, style: "display: block" %>
    <%= form.text_field :metodo_pago %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.text_field :estado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/venta/_venta.html.erb
<div id="<%= dom_id ventum %>">
  <p>
    <strong>Cliente:</strong>
    <%= ventum.cliente_id %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= ventum.fecha %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= ventum.total %>
  </p>

  <p>
    <strong>Metodo pago:</strong>
    <%= ventum.metodo_pago %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= ventum.estado %>
  </p>

</div>

app/views/venta/edit.html.erb
<% content_for :title, "Editing ventum" %>

<h1>Editing ventum</h1>

<%= render "form", venta: @venta %>

<br>

<div>
  <%= link_to "Show this ventum", @venta %> |
  <%= link_to "Back to venta", venta_path %>
</div>

app/views/venta/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Venta" %>

<h1>Venta</h1>

<div id="venta">
  <% @venta.each do |ventum| %>
    <%= render ventum %>
    <p>
      <%= link_to "Show this ventum", ventum %>
    </p>
  <% end %>
</div>

<%= link_to "New ventum", new_ventum_path %>

app/views/venta/new.html.erb
<h1>New Venta</h1>
<%= render 'form' %>
<%= link_to 'Back', venta_index_path %> <!-- Asegúrate de que esta ruta exista -->

app/views/venta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ventum %>

<div>
  <%= link_to "Edit this ventum", edit_ventum_path(@ventum) %> |
  <%= link_to "Back to venta", venta_path %>

  <%= button_to "Destroy this ventum", @ventum, method: :delete %>
</div>