config/routes.rb
Rails.application.routes.draw do
  resources :envios
  resources :categoria
  resources :detalles_venta
  resources :venta
  resources :productos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/envio.rb
class Envio < ApplicationRecord
  belongs_to :venta
end

app/controllers/envios_controller.rb
class EnviosController < ApplicationController
  before_action :set_envio, only: %i[ show edit update destroy ]

  # GET /envios or /envios.json
  def index
    @envios = Envio.all
  end

  # GET /envios/1 or /envios/1.json
  def show
  end

  # GET /envios/new
  def new
    @envio = Envio.new
  end

  # GET /envios/1/edit
  def edit
  end

  # POST /envios or /envios.json
  def create
    @envio = Envio.new(envio_params)

    respond_to do |format|
      if @envio.save
        format.html { redirect_to @envio, notice: "Envio was successfully created." }
        format.json { render :show, status: :created, location: @envio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @envio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /envios/1 or /envios/1.json
  def update
    respond_to do |format|
      if @envio.update(envio_params)
        format.html { redirect_to @envio, notice: "Envio was successfully updated." }
        format.json { render :show, status: :ok, location: @envio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @envio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /envios/1 or /envios/1.json
  def destroy
    @envio.destroy!

    respond_to do |format|
      format.html { redirect_to envios_path, status: :see_other, notice: "Envio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_envio
      @envio = Envio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def envio_params
      params.require(:envio).permit(:venta_id, :direccion_envio, :fecha_envio, :estado)
    end
end

app/helpers/envios_helper.rb
module EnviosHelper
end

app/views/envios/_envio.html.erb
<div id="<%= dom_id envio %>">
  <p>
    <strong>Venta:</strong>
    <%= envio.venta_id %>
  </p>

  <p>
    <strong>Direccion envio:</strong>
    <%= envio.direccion_envio %>
  </p>

  <p>
    <strong>Fecha envio:</strong>
    <%= envio.fecha_envio %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= envio.estado %>
  </p>

</div>

app/views/envios/_form.html.erb
<%= form_with(model: envio) do |form| %>
  <% if envio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(envio.errors.count, "error") %> prohibited this envio from being saved:</h2>

      <ul>
        <% envio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :venta_id, style: "display: block" %>
    <%= form.number_field :venta_id %>
  </div>

  <div>
    <%= form.label :direccion_envio, style: "display: block" %>
    <%= form.text_field :direccion_envio %>
  </div>

  <div>
    <%= form.label :fecha_envio, style: "display: block" %>
    <%= form.date_field :fecha_envio %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.text_field :estado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/envios/edit.html.erb
<% content_for :title, "Editing envio" %>

<h1>Editing envio</h1>

<%= render "form", envio: @envio %>

<br>

<div>
  <%= link_to "Show this envio", @envio %> |
  <%= link_to "Back to envios", envios_path %>
</div>

app/views/envios/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Envios" %>

<h1>Envios</h1>

<div id="envios">
  <% @envios.each do |envio| %>
    <%= render envio %>
    <p>
      <%= link_to "Show this envio", envio %>
    </p>
  <% end %>
</div>

<%= link_to "New envio", new_envio_path %>

app/views/envios/new.html.erb
<% content_for :title, "New envio" %>

<h1>New envio</h1>

<%= render "form", envio: @envio %>

<br>

<div>
  <%= link_to "Back to envios", envios_path %>
</div>

app/views/envios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @envio %>

<div>
  <%= link_to "Edit this envio", edit_envio_path(@envio) %> |
  <%= link_to "Back to envios", envios_path %>

  <%= button_to "Destroy this envio", @envio, method: :delete %>
</div>